services:
  - type: web
    name: qr-threat-scanner
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    branch: main
    runtime: python
    region: oregon
